# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.box = "ubuntu/bionic64"
  config.vm.box = "generic/ubuntu1804"

  memory_mb = 2048

  zk = {
    'zk-1' => "192.168.5.100",
    #'zk-2' => "192.168.5.101",
    #"zk-3" => "192.168.5.102"
  }

  solr = {
    'solr-1' => "192.168.5.200",
    'solr-2' => "192.168.5.201",
    'solr-3' => "192.168.5.202",
  }

  zk.each_with_index do |(short_name, ip), idx|
    config.vm.define short_name do |host|
      host.vm.network :private_network, ip: ip, virtualbox__intnet: true
      host.vm.hostname = short_name
      host.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", memory_mb]
      end
      host.vm.provision :ansible do |ansible|
        ansible.playbook = "provision-zk.yml"
        ansible.extra_vars = {
          zk_node_seq: idx + 1,
          zk_ip_addresses: zk.values,
          solr_ip_addresses: solr.values
        }
      end
    end
  end

  solr.each_with_index do |(short_name, ip), idx|
    config.vm.define short_name do |host|
      host.vm.network :private_network, ip: ip, virtualbox__intnet: true
      host.vm.hostname = short_name
      host.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", memory_mb]
      end
      host.vm.provision :ansible do |ansible|
        ansible.playbook = "provision-solr.yml"
        ansible.extra_vars = {
          zk_node_seq: idx + 1,
          zk_ip_addresses: zk.values,
          solr_ip_addresses: solr.values
        }
      end
    end
  end


end
